### ISSUE TITLE
云盘导入功能歌曲能传专辑封面字段参数吗

### ISSUE THREAD

**Issue by 0xc0ee** [Cinvin/myuserscripts#10]
上传一些网易云删库的被封歌曲，无法使用歌曲ID进行纠错，有办法将上传到云盘无封面的歌曲修改封面吗？

**Comment by Cinvin** [comment]
没办法 改封面只有歌曲ID匹配这一个办法
就算修改文件的音乐标签加上封面再上传也不会显示

**Comment by nightwings999** [comment]
> 没办法 改封面只有歌曲ID匹配这一个办法 就算修改文件的音乐标签加上封面再上传也不会显示

科技与狠活！感谢大佬，对DJ来说使用非常方便。但有个问题不知道能否解决：把歌曲转存云盘再下载后文件名没有艺人信息，文件名只保留了歌曲名。可否把文件名改进为【歌名-艺人名.文件格式】的命名方式 ：）再次感谢

**Comment by Cinvin** [comment]
> 科技与狠活！感谢大佬，对DJ来说使用非常方便。但有个问题不知道能否解决：把歌曲转存云盘再下载后文件名没有艺人信息，文件名只保留了歌曲名。可否把文件名改进为【歌名-艺人名.文件格式】的命名方式 ：）再次感谢

转存时文件名已改进为 `歌手-歌名` (因为比`歌名-歌手`更常用)

**Comment by nightwings999** [comment]
> > 科技与狠活！感谢大佬，对DJ来说使用非常方便。但有个问题不知道能否解决：把歌曲转存云盘再下载后文件名没有艺人信息，文件名只保留了歌曲名。可否把文件名改进为【歌名-艺人名.文件格式】的命名方式 ：）再次感谢
> 
> 转存时文件名已改进为 `歌手-歌名` (因为比`歌名-歌手`更常用)

太感谢了！！！想打赏！！！
