### ISSUE TITLE
是Svip但下载没有超清母带，找不到高音质试听在哪

### ISSUE THREAD

**Issue by bestxzlme** [Cinvin/myuserscripts#11]
大佬好，请问一下已经是SVIP了但是下载歌曲没有显示超清母带，还有找不到高音质试听在哪里？希望大佬解答。

![屏幕截图 2024-04-15 172557](https://github.com/Cinvin/myuserscripts/assets/148630055/057130de-4884-4771-a2fc-47291a8b01a7)

**Comment by Cinvin** [comment]
尝试修复了这个BUG，更新脚本再试试看
高音质试听设置 见下图
<img width="571" alt="截屏2024-04-15 18 21 40" src="https://github.com/Cinvin/myuserscripts/assets/31982712/bd1bb74e-304e-4227-8bd0-b4f05489f937">

**Comment by bestxzlme** [comment]
感谢大佬，能下载了
