### ISSUE TITLE
沉浸环绕声音质获取

### ISSUE THREAD

**Issue by SSWRF** [Cinvin/myuserscripts#16]
近期网易云无论是客户端还是网页脚本等方式直接选择沉浸环绕声，默认获取到的沉浸环绕声都是双声道的残缺版，但选择超清母带音质下载一首最高只有沉浸环绕声的歌曲可以正常fallback到到5.1声道版本的沉浸环绕声，请问能否在脚本中也实现此功能，感激不尽！

**Comment by Cinvin** [comment]
你说的5.1声道版本实际上应该是指杜比全景声吧?
https://music.163.com/#/playlist?id=7782055324
这个是svip可以获取到的，手机客户端音质选项里但又隐藏起来的音质。 
尝试增加了这个音质，但我没有svip无法验证，
可以用下面的代码试试，帮我验证一下吗。
[杜比.txt](https://github.com/user-attachments/files/16823754/default.txt)

**Comment by SSWRF** [comment]
谢谢大佬，确实可以获取到杜比，非常感谢您这么快更新
![Memories - Conan Gray - 单曲 - 网易云音乐 和另外 3 个页面 - 个人 - Microsoft​ Edge 2024_8_31 15_40_14](https://github.com/user-attachments/assets/89cf0c70-39d7-45ec-9280-44b13dbbca19)
沉浸环绕声和杜比全景声是两个不同的音质，前者是网易云对普通双声道音频用算法拓展的，目前无论是客户端还是网页对于有沉浸环绕声没有杜比全景声的歌曲获取到的音乐文件只有两个声道，码率也明显偏低，只有默认下载音质是超清母带歌曲没有超清母带自动降级至沉浸环绕声下载时才是正常5.1声道，猜测是网易云官方加了限制
![Memories - Conan Gray - 单曲 - 网易云音乐 和另外 3 个页面 - 个人 - Microsoft​ Edge 2024_8_31 15_46_34](https://github.com/user-attachments/assets/da21c045-8ff8-4af2-8777-b1ea645d8bdf)
