### ISSUE TITLE
下载有问题

### ISSUE THREAD

**Issue by Vucius** [Cinvin/myuserscripts#18]
我用的是Vivaldi浏览器 不过应该和浏览器关系不大
在歌曲页面点击下载 比如这首歌[Wake Me Up](https://music.163.com/#/song?id=1479799224)
会触发IDM弹窗 并且是弹窗两个 然后浏览器页面的弹窗是显示下载失败
更重要的是下载的文件信息不对。文件名是这样的
obj_wo3DlMOGwrbDjj7DisKw_19641664386_7b72_a140_711d_79926898c54bf41f549ebed276636964.mp3
并且文件属性里没有对应的歌手歌曲
![111](https://github.com/user-attachments/assets/e6769f33-d20a-4cba-903f-3aab14f4e7f9)

如果是在歌单页面批量下载 也是一样会出现上述情况。不过 有不同的地方，就是批量下载可以选择下载歌词下来
这个歌词文件 至少名称没问题

**Comment by Cinvin** [comment]
IDM是直接捕捉下载链接，没有重命名处理。
我脚本调用的是Tampermonkey插件的下载API，会在保存的时候进行重命名。
我下了个Vivaldi试试是可以下载的。
<img width="1120" alt="截屏2024-09-03 00 09 25" src="https://github.com/user-attachments/assets/52fa1fd0-66e7-44a4-a9f4-cb88e15176e9">
不知道IDM会不会有影响？关了试试？
