### ISSUE TITLE
似乎只有热狗的快速上传没有文件

### ISSUE THREAD

**Issue by superwong777** [Cinvin/myuserscripts#20]
如图，麻烦开发者排查一下问题所在～

**Comment by Cinvin** [comment]
热狗我只有20几首歌，可能你的云盘刚好以前全部都上传过了，打开就没有可上传的了。

**Comment by superwong777** [comment]
> 热狗我只有20几首歌，可能你的云盘刚好以前全部都上传过了，打开就没有可上传的了。

没，我这里之前没有上传过，我找到一个链接不过没有做匹配，看看哥能否处理一下？https://www.aliyundrive.com/s/BsRkVKKYW9p

**Comment by superwong777** [comment]
![longshot20241005224427](https://github.com/user-attachments/assets/df91159e-5e29-45e7-b547-270822f0f7a8)

**Comment by superwong777** [comment]
> ![longshot20241005224427](https://private-user-images.githubusercontent.com/69034385/373880751-df91159e-5e29-45e7-b547-270822f0f7a8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjgxMzk3OTEsIm5iZiI6MTcyODEzOTQ5MSwicGF0aCI6Ii82OTAzNDM4NS8zNzM4ODA3NTEtZGY5MTE1OWUtNWUyOS00NWU3LWI1NDctMjcwODIyZjBmN2E4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDA1VDE0NDQ1MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWNhMjhkYTdkMmQ5ZGE4MzhmZWMxYzIwMDA0M2E0ZTc5MGIxYTgwNWE2ZTdiMmQ2MTBhNWE5MmY2ZWQ2ZDhkZmImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.ISet0Y2uXNYTgVVDiAvZXwBSO8_HN3uyAEncD0jUViQ)

点击热狗的歌曲就会显示没有歌曲

**Comment by Cinvin** [comment]
啊确实没有，仔细看了下我这只有和别人合唱的，没有专门爬过。
热狗网易云是有版权的，我建议是领个7天VIP用「批量转存云盘」功能来上传吧。
在那些VIP相关的歌单的评论区很容易领到。
例如 [黑胶VIP爱听榜](https://music.163.com/#/playlist?id=5453912201)
「快速上传」基本上不会再加资源了，太费劲了。😟
