### ISSUE TITLE
账号冻结

### ISSUE THREAD

**Issue by cloud666666666** [Cinvin/myuserscripts#21]
听歌打卡300首会封号吗

**Comment by Cinvin** [comment]
这个脚本目前还没事吧，有人被冻结吗？至少我现在没事。
目前冻结问题网易云检测的是登陆api, 而脚本根本就不涉及登陆功能。
而且脚本是借用网页端本身来调用api，网易云会视为网页端的调用。
不过要是网易云以后检测再变态点还是能查出来的。要是被检测听歌间隔就完了，目前1秒听完300首歌太变态了。
现在大家就闷声发财吧。

**Comment by sootaeng** [comment]
我被冻结了，用了大概三四天的听歌量打卡，今天上午被冻结了三天，找客服说违反社区准则。

**Comment by acgpiano** [comment]
我的也被冻结了, 只要刷了播放量, 然后会被强制改密码, 改几次之后直接冻结了

**Comment by sootaeng** [comment]
> 我的也被冻结了, 只要刷了播放量, 然后会被强制改密码, 改几次之后直接冻结了

没错，我也是被强制下线然后强制改密码，改了两次，今天上午给我冻结了，但是智能回复说的是我上传或发布了违规内容，可是我并没有发布上传任何违规内容，然后我联系人工客服，她回复我说确定不是永久冻结，三天以后解封。

**Comment by acgpiano** [comment]
> > 我的也被冻结了, 只要刷了播放量, 然后会被强制改密码, 改几次之后直接冻结了
> 
> 没错，我也是被强制下线然后强制改密码，改了两次，今天上午给我冻结了，但是智能回复说的是我上传或发布了违规内容，可是我并没有发布上传任何违规内容，然后我联系人工客服，她回复我说确定不是永久冻结，三天以后解封。

看来网易云现在检测到了, 还是谨慎使用, 我是音乐人, 里面收益几千块钱直接没法提现

**Comment by Cinvin** [comment]
> > > 我的也被冻结了, 只要刷了播放量, 然后会被强制改密码, 改几次之后直接冻结了
> > 
> > 
> > 没错，我也是被强制下线然后强制改密码，改了两次，今天上午给我冻结了，但是智能回复说的是我上传或发布了违规内容，可是我并没有发布上传任何违规内容，然后我联系人工客服，她回复我说确定不是永久冻结，三天以后解封。
> 
> 看来网易云现在检测到了, 还是谨慎使用, 我是音乐人, 里面收益几千块钱直接没法提现

兄弟，你要跟客服说使用插件是为了刷「账号听歌数量」没有刷「歌曲播放量」，使用的歌曲ID不是真正的歌曲ID，因此不会获取经济收益。并叫客服查后台数据验证。不然可能真的无法提现了。看图...
![aedb-e0444d4c48ebe5fd2cd0cae3c66c6a8a](https://github.com/user-attachments/assets/6351fb3e-435e-4e97-902f-a6a2c321b496)
