### ISSUE TITLE
最新云盘无法上传音乐

### ISSUE THREAD

**Issue by adddp** [Cinvin/myuserscripts#22]
账号原有的100G云盘满了，最近SVIP会员有6T空间容量了，用插件保存歌曲时全部都提示失败 换了几个歌单都是一样，但用官方客户端上传是没问题的，希望能支持SVIP的6T云盘空间

**Comment by adddp** [comment]
如果账号原有的100G没满的话 用这个插件还是能上传的，只是满了之后不会上传到SVIP的6T云盘空间

**Comment by Cinvin** [comment]
这个SVIP6T空间具体是啥，网上冲浪了一圈没找到，你不会是被灰度测试了吧?因为云盘歌多被选上了？
云盘容量会显示6.1T吗?会是像买扩容那样SVIP到期了歌还在只是无法上传吗？
如果只是少数人有的话我也做不了什么，而且我也没SVIP。
你可以自己改代码里的接口参数试试？
<img width="440" alt="截屏2024-10-10 14 54 19" src="https://github.com/user-attachments/assets/441e1f7d-58c7-4c58-be56-cbd46a3552ff">
<img width="415" alt="截屏2024-10-10 14 55 42" src="https://github.com/user-attachments/assets/1f6b35e9-7ce6-4279-aa68-db30bd3afdc0">
以前好奇我试过改成1、2、3但是上传不了。说不定你可以上传。
你也是牛逼，之前扩容的2T都用完了？我才传了了5w首都不到。

**Comment by adddp** [comment]
> 这个SVIP6T空间具体是啥，网上冲浪了一圈没找到，你不会是被灰度测试了吧?因为云盘歌多被选上了？ 云盘容量会显示6.1T吗?会是像买扩容那样SVIP到期了歌还在只是无法上传吗？ 如果只是少数人有的话我也做不了什么，而且我也没SVIP。 你可以自己改代码里的接口参数试试？ <img alt="截屏2024-10-10 14 54 19" width="440" src="https://private-user-images.githubusercontent.com/31982712/375257252-441e1f7d-58c7-4c58-be56-cbd46a3552ff.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg1NDUyMjcsIm5iZiI6MTcyODU0NDkyNywicGF0aCI6Ii8zMTk4MjcxMi8zNzUyNTcyNTItNDQxZTFmN2QtNThjNy00YzU4LWJlNTYtY2JkNDZhMzU1MmZmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDEwVDA3MjIwN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTY0MGMxNTJmM2IzNDU3MTZhOTRmY2QzYTI4YjM5N2Y5ZDAxM2JkYjE3ZWRmOGJiMzkwNjcwYzU2OTcyOTU0NDYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.22mO4S4cPEGRVbbM8s7NrErKZIHvoCsJoFVLxklARks"> <img alt="截屏2024-10-10 14 55 42" width="415" src="https://private-user-images.githubusercontent.com/31982712/375257765-1f6b35e9-7ce6-4279-aa68-db30bd3afdc0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg1NDUyMjcsIm5iZiI6MTcyODU0NDkyNywicGF0aCI6Ii8zMTk4MjcxMi8zNzUyNTc3NjUtMWY2YjM1ZTktN2NlNi00Mjc5LWFhNjgtZGIzMGJkM2FmZGMwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDEwVDA3MjIwN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTRjYTA1YzdmYzkwZTc3ZDJkYTBkMjEzMzVlNDI2OTZkNjMxYWI5NWZjYzAxMDdiNjY0OTQ5ZDA5YTZjZmI1NmMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.gTK_zIFpWeS6M6VCkETLIZnGVDdSTX0dgx9KkrvCpYY"> 以前好奇我试过改成1、2、3但是上传不了。说不定你可以上传。 你也是牛逼，之前扩容的2T都用完了？我才传了了5w首都不到。




这个6T的空间是这两天才更新的SVIP权益，所以网上还没有人讨论这个，客户端更新到最新版后才能看到这个容量，我刚刚照着你说的改了参数  也是无法上传，这个权益开放之后 后续应该会有更多人上传超过100G的空间  ，现在算小众需求 不过以后应该不算小众需求。

![最新版网易云盘](https://github.com/user-attachments/assets/ab6a21a0-de42-4ba7-bbb8-ca8677374c18)

**Comment by Cinvin** [comment]
如果是客户端更新到最新版后才能看到这个容量的话。
你可以改代码的版本号到最新的试试。
<img width="340" alt="截屏2024-10-10 15 49 38" src="https://github.com/user-attachments/assets/ee26b60c-b7a6-40d2-9291-152dafb9f489">
网易云不同的版本号信息接口返回的内容是不同的。

**Comment by adddp** [comment]
> 如果是客户端更新到最新版后才能看到这个容量的话。 你可以改代码的版本号到最新的试试。 <img alt="截屏2024-10-10 15 49 38" width="340" src="https://private-user-images.githubusercontent.com/31982712/375278164-ee26b60c-b7a6-40d2-9291-152dafb9f489.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg1NDcyNjksIm5iZiI6MTcyODU0Njk2OSwicGF0aCI6Ii8zMTk4MjcxMi8zNzUyNzgxNjQtZWUyNmI2MGMtYjdhNi00MGQyLTkyOTEtMTUyZGFmYjlmNDg5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDEwVDA3NTYwOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWU3M2ZlOTU0YmIyMjA1ZDY0MjRkNzkyMjJkZjA0YjQyOGVmZDNiZDFiMzlmZTIxNDYyY2U5OTU5NmIyNGI5NmImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.wD_TmRlaIHid59pxMYDxxREDkyAkpEm-FCaaK5uY2j4"> 网易云不同的版本号信息接口返回的内容是不同的。

十分感谢，我把版本号改为最新版本号3.0.4后仍不行，最后直接改为3.4  并且将手机端版本也改为最新版后可以上传了。
