### ISSUE TITLE
更新后仍然无法上传

### ISSUE THREAD

**Issue by luozongkai** [Cinvin/myuserscripts#23]
如题所示，我在已经是svip的情况下云盘空间到100G后就上传不动了
![1](https://github.com/user-attachments/assets/9ed1a2c3-7e03-4c5c-ba29-6b71814f3d35)

**Comment by adddp** [comment]
那证明你没有更新油猴脚本到最新版

**Comment by luozongkai** [comment]
> 那证明你没有更新油猴脚本到最新版

我今天第一次使用脚本默认下载最新（4.1.3），所以不存在你说的问题。。。

**Comment by luozongkai** [comment]
> 那证明你没有更新油猴脚本到最新版

我今天第一次使用脚本默认会下载最新版（4.1.3），所以不存在你说的问题。。。

**Comment by adddp** [comment]
> > 那证明你没有更新油猴脚本到最新版
> 
> 我今天第一次使用脚本默认会下载最新版（4.1.3），所以不存在你说的问题。。。


我目前用的就是最新版，没有问题，请检查你的环境

**Comment by luozongkai** [comment]
将暴力猴更改为tampermonkey后已解决。
