### ISSUE TITLE
新版4.2的部分bug

### ISSUE THREAD

**Issue by adddp** [Cinvin/myuserscripts#24]
使用最新版4.2时会出现几个问题：
1. 偶现到第三部 “文件导入云盘”时卡主，没有进行开始上传的步骤（这个问题不会导致变未登录 只是一直不进行下一步，只有个别歌单会出现）
2. 上传到一半时会卡主，然后登录状态变成了未登录（不确定卡主是不是这个原因导致的，但刷新页面后又变回了已登录状态，刷新后再重新保存到一半又变回未登录 刷新后又恢复 以此循环，任何歌单都有可能出现这个问题，常出现在歌单歌曲较多或浏览器同时打开多标签页时）

以上问题都是出现在新版的，4.2以下的版本未发现这些问题

![微信图片_20241018083529](https://github.com/user-attachments/assets/7ee99aa4-28e7-4421-8a99-a25048dd3595)
![微信图片_20241018083542](https://github.com/user-attachments/assets/2675968b-0e51-49fe-afa9-680b8bbe16d1)
![微信图片_20241018084410](https://github.com/user-attachments/assets/859915fb-7c05-4720-9b58-e08afe6d584d)

**Comment by Cinvin** [comment]
第1个问题已改，第2个问题应该是第1个问题造成。
请更新试试看。

**Comment by adddp** [comment]
部分歌单会报这个错误，比如这个歌单：https://music.163.com/#/playlist?id=402722678

错误提示：TypeError: Cannot read properties of null (reading 'toLowerCase')

![image](https://github.com/user-attachments/assets/676b0897-ccf9-45ec-9576-2695f2292ddb)

**Comment by Cinvin** [comment]
bug改了，请更新试试看。
是[https://music.163.com/#/song?id=521416705](https://music.163.com/#/song?id=521416705)这种奇怪的歌导致的。

**Comment by adddp** [comment]
> bug改了，请更新试试看。 是https://music.163.com/#/song?id=521416705这种奇怪的歌导致的。

十分感谢
