### ISSUE TITLE
快传云盘信息，已下架歌曲怎么获得md5等信息的呢

### ISSUE THREAD

**Issue by dulongxiang** [Cinvin/myuserscripts#27]
请问作者，已经下架的歌曲比如周杰伦的，是怎能获得秒传的信息的呢

**Comment by Cinvin** [comment]
那些不是网易云的，是我自己上传云盘的。

**Comment by dulongxiang** [comment]
嗯嗯，我的意思是：假如你有一个本地歌曲A，也有这个歌的md5等信息，把这首歌传到云盘上，是怎么和网易云的匹配上的

**Comment by Cinvin** [comment]
网易云有【云盘歌曲信息匹配纠正】接口
云盘歌曲调用这个接口，就可以改成对应的歌曲ID
[网易云怎么匹配歌曲-百度经验](https://jingyan.baidu.com/article/5225f26b51db29a7fb090816.html)
所以是上传完成后再调用这个接口匹配
