### ISSUE TITLE
网易云里面的歌单

### ISSUE THREAD

**Issue by li110120999** [Cinvin/myuserscripts#29]
是要开网易云的会员歌单才能批量转存到云盘里吗 歌单里vip的歌好像转存不了

**Comment by Cinvin** [comment]
是的，要vip。也不必开会员，你去领个7天黑胶礼品卡也行。

**Comment by li110120999** [comment]
刚开的黑胶svip  插件好像是检测不到空间变6T了  提示用户云盘空间不足  这样怎么解决啊
