### ISSUE TITLE
xxx 音质提升失败

### ISSUE THREAD

**Issue by xueba0458** [Cinvin/myuserscripts#30]
xxx音质提升失败，全部都是提升音质失败！不管选Hi-Res还是无损都会提升失败！我转存时选择的是极高音质，转存到云盘的也都是极高音质！

我已经是SVIP黑胶用户！！！

```json
{data: false, code: 400, message: '当前文件不支持纠错'}
```

**Comment by Cinvin** [comment]
报错问题已修复，请更新试试看。
转存时选择的是极高音质，转存到云盘的当然就是极高音质，这个设置和app的音质设置是一样的。
有6T空间也没必要存极高音质吧。据统计有一半的用户是能听出320k和无损的差别的。

**Comment by xueba0458** [comment]
> 报错问题已修复，请更新试试看。
> 转存时选择的是极高音质，转存到云盘的当然就是极高音质，这个设置和app的音质设置是一样的。
> 有6T空间也没必要存极高音质吧。据统计有一半的用户是能听出320k和无损的差别的。

虽然听不出来，但是得有[狗头保命]
