### ISSUE TITLE
自己找资源补全了杰伦的歌到438首

### ISSUE THREAD

**Issue by Ctrl-Ling** [Cinvin/myuserscripts#7]
这个是歌单https://music.163.com//m/playlist?id=8741891297&userid=7818513
[周杰伦438首-网易云云盘插件导入.json](https://github.com/Cinvin/myuserscripts/files/13161104/438.-.json)

**Comment by Cinvin** [comment]
感谢提供，已经补充了

**Comment by Ctrl-Ling** [comment]
> 感谢提供，已经补充了
补充杰伦的新歌圣诞星
{"data":[{"id":2110762614,"size":40015797,"ext":"flac","bitrate":1752,"md5":"cdc661890cde224d3740347258118272"}]}

**Comment by Cinvin** [comment]
才看到，我已经放自己找的上去了。

**Comment by Ctrl-Ling** [comment]
> 才看到，我已经放自己找的上去了。

又补充了14首live
[Uploading 周杰伦452首-网易云云盘插件导入.json…]()

**Comment by Ctrl-Ling** [comment]
> 才看到，我已经放自己找的上去了。

又补充了14首live
[周杰伦452首-网易云云盘插件导入.json](https://github.com/Cinvin/myuserscripts/files/14155461/452.-.json)
